### ISSUE TITLE
Question about the paper(arXiv ver.)

### ISSUE THREAD

**Issue by countywest** [xiaogangw-zz/cascaded-point-completion#2]
Hello~ I read your paper (https://arxiv.org/abs/2004.03327), and I want to ask a question about something not clear for me.

In the figure 2, Feature Extraction module outputs per-point features( dimension: N x C ), but I think Maxpooling condenses the per-point features( N x C ) to a global feature vector( C-dimensional ). For example, pointnet outputs a 1024-dimensional vector for each shape, because Maxpooling layer operates on the last layer( N x 1024 ). Is the figure 2 correct?

**Comment by xiaogangw-zz** [comment]
@countywest  Thanks for your interest on our paper and point it out, we have updated it on arXiv.

**Comment by countywest** [comment]
@xiaogangw Sorry, I can't find any difference from the previous version. How can I access the updated version?

**Comment by xiaogangw-zz** [comment]
@countywest Available now, since it needs time to update for arXiv submission.

**Comment by countywest** [comment]
@xiaogangw Thanks for your fast reply!
